fileVersion: 1
id: "33"
mappingDefinitions:
  ALLISON_DB2:
    database: ALLISON_DB2
    schema: SOURCE
  SRC:
    database: ALLISON_DB2
    schema: SOURCE
  WORK:
    database: ALLISON_DB
    schema: TEST_VIDEO
name: Prod
type: Environment